import type {
  GlobalTask,
  WorkbenchSnapshot,
} from "../contracts";

const generatedAt = "2026-08-03T14:32:00+08:00";

export const globalTasks: GlobalTask[] = [
  {
    priority: "P0",
    id: "DEV-07",
    version: 12,
    goalId: "GOAL-2407",
    title: "Web 审批工作区",
    kind: "issue",
    stage: "review",
    status: { code: "review", label: "Review", tone: "warning" },
    progress: { percent: 92, updatedAt: generatedAt },
    attention: {
      required: true,
      count: 1,
      severity: "warning",
      headline: "权限边界例外待人工决定",
      rankingReason: "截止 15:00 · 阻塞 Wave 4",
      impact: "影响 Production V1 发布门禁",
      dueAt: "2026-08-03T15:00:00+08:00",
      blockedTaskCount: 1,
    },
    execution: {
      actorType: "worker",
      actorId: "W2",
      actorLabel: "W2 · Reviewer",
      elapsedSeconds: 1448,
      nextCheckpoint: "审查边界证据",
    },
    action: { id: "review_evidence", label: "审查证据", available: true, requiredRole: "Approver", targetView: "run" },
    detail: {
      dependency: "DEV-06 已完成",
      evidence: "3 项验证通过 · 1 项待判断",
      workspace: "worktree/DEV-07",
    },
  },
  {
    priority: "P0",
    id: "ORD-02",
    version: 8,
    goalId: "GOAL-2406",
    title: "游标回退边界归并",
    kind: "gate",
    stage: "waiting",
    status: { code: "human_gate", label: "待人工", tone: "warning" },
    progress: { percent: 44, updatedAt: generatedAt },
    attention: {
      required: true,
      count: 2,
      severity: "warning",
      headline: "2 个边界问题待回答",
      rankingReason: "已等待 2h 15m · 阻塞 3 项",
      impact: "决定订单服务最小交付范围",
      waitingSeconds: 8100,
      blockedTaskCount: 3,
    },
    execution: {
      actorType: "role",
      actorLabel: "Goal Planner",
      elapsedSeconds: 8100,
      nextCheckpoint: "确认回退策略",
    },
    action: { id: "answer_questions", label: "回答问题", available: true, requiredRole: "Approver", targetView: "clarify" },
    detail: {
      dependency: "Goal Contract rev.4",
      evidence: "2 个问题 · 1 项风险提示",
      workspace: "order-service/planning",
    },
  },
  {
    priority: "P1",
    id: "ID-10",
    version: 5,
    goalId: "GOAL-2403",
    title: "集成环境凭据恢复",
    kind: "scheduling",
    stage: "blocked",
    status: { code: "blocked", label: "阻塞", tone: "danger" },
    progress: { percent: 28, updatedAt: generatedAt },
    attention: {
      required: true,
      count: 1,
      severity: "blocking",
      headline: "临时凭据不可用",
      rankingReason: "2 个 Worker 不可领取 · 已等待 47m",
      impact: "统一权限模型迁移暂停",
      waitingSeconds: 2820,
      blockedTaskCount: 2,
    },
    execution: {
      actorType: "scheduler",
      actorLabel: "Scheduler",
      elapsedSeconds: 2820,
      nextCheckpoint: "凭据管理员处理",
    },
    action: {
      id: "resolve_blocker",
      label: "处理阻塞",
      available: true,
      requiredRole: "Operator",
      successMessage: "ID-10 阻塞详情已打开",
    },
    detail: {
      dependency: "integration-credential",
      evidence: "最近 3 次连接均失败",
      workspace: "identity-platform/integration",
    },
  },
  {
    priority: "P1",
    id: "DEV-09",
    version: 4,
    goalId: "GOAL-2407",
    title: "生产恢复演练",
    kind: "issue",
    stage: "blocked",
    status: { code: "resource_wait", label: "资源等待", tone: "danger" },
    progress: { percent: 12, updatedAt: generatedAt },
    attention: {
      required: true,
      count: 1,
      severity: "blocking",
      headline: "integration-db 独占窗口未确认",
      rankingReason: "最早窗口 20:00 · 已等待 31m",
      impact: "影响 Production V1 演练排期",
      waitingSeconds: 1860,
      blockedTaskCount: 1,
    },
    execution: {
      actorType: "scheduler",
      actorLabel: "Scheduler",
      elapsedSeconds: 1860,
      nextCheckpoint: "确认独占窗口",
    },
    action: { id: "inspect_schedule", label: "查看调度", available: true, requiredRole: "Viewer", targetView: "scheduler" },
    detail: {
      dependency: "DEV-08 · integration-db",
      evidence: "与 ORD-03 存在资源冲突",
      workspace: "ai-dev-harness/recovery",
    },
  },
  {
    priority: "P1",
    id: "DEV-06",
    version: 18,
    goalId: "GOAL-2407",
    title: "AutoDev 模型路由",
    kind: "issue",
    stage: "running",
    status: { code: "running", label: "执行中", tone: "info" },
    progress: { percent: 76, completedUnits: 84, totalUnits: 112, updatedAt: generatedAt },
    attention: {
      required: false,
      count: 0,
      severity: "none",
      headline: "任务正常推进",
      rankingReason: "暂无人工门禁或执行阻塞",
      impact: "预计 8 分钟后完成测试",
    },
    execution: {
      actorType: "worker",
      actorId: "W1",
      actorLabel: "W1 · Codex",
      elapsedSeconds: 1122,
      nextCheckpoint: "测试完成",
    },
    action: { id: "inspect_run", label: "查看执行", available: true, requiredRole: "Viewer", targetView: "run" },
    detail: {
      dependency: "DEV-04 已完成",
      evidence: "单测 46/46 通过",
      workspace: "worktree/DEV-06",
    },
  },
  {
    priority: "P2",
    id: "ID-11",
    version: 9,
    goalId: "GOAL-2403",
    title: "权限策略兼容层迁移",
    kind: "issue",
    stage: "waiting",
    status: { code: "budget_queue", label: "预算排队", tone: "neutral" },
    progress: { percent: 61, completedUnits: 18, totalUnits: 24, updatedAt: generatedAt },
    attention: {
      required: false,
      count: 0,
      severity: "none",
      headline: "任务正常推进",
      rankingReason: "按预算策略等待下个执行窗口",
      impact: "已完成 18/24 条策略回放",
    },
    execution: {
      actorType: "scheduler",
      actorLabel: "Scheduler",
      elapsedSeconds: 787,
      nextCheckpoint: "W3 槽位释放",
    },
    action: { id: "inspect_schedule", label: "查看调度", available: true, requiredRole: "Viewer", targetView: "scheduler" },
    detail: {
      dependency: "ID-09 已完成",
      evidence: "18/24 条策略通过",
      workspace: "worktree/ID-11",
    },
  },
  {
    priority: "P2",
    id: "DEV-08",
    version: 2,
    goalId: "GOAL-2407",
    title: "Goal Verifier 与交付报告",
    kind: "issue",
    stage: "waiting",
    status: { code: "dependency_wait", label: "等待依赖", tone: "neutral" },
    progress: { percent: 0, updatedAt: generatedAt },
    attention: {
      required: false,
      count: 0,
      severity: "none",
      headline: "任务正常推进",
      rankingReason: "按计划等待上游任务完成",
      impact: "DEV-06、DEV-07 完成后自动领取",
    },
    execution: {
      actorType: "scheduler",
      actorLabel: "Scheduler",
      elapsedSeconds: 720,
      nextCheckpoint: "等待 DEV-06、DEV-07",
    },
    action: { id: "inspect_schedule", label: "查看调度", available: true, requiredRole: "Viewer", targetView: "scheduler" },
    detail: {
      dependency: "DEV-06 · DEV-07",
      evidence: "依赖 DAG 健康",
      workspace: "尚未创建",
    },
  },
];

export const workbenchSnapshot: WorkbenchSnapshot = {
  schemaVersion: "workbench.v1",
  revision: 21,
  generatedAt,
  summary: {
    taskCounts: {
      all: 7,
      attention: 4,
      running: 1,
      review: 1,
      blocked: 2,
      waiting: 3,
    },
    metrics: [
      {
        id: "attention",
        label: "需处理",
        value: "4",
        detail: "人工介入",
        detailEmphasis: "2 项 P0",
        targetFilter: "attention",
      },
      {
        id: "running",
        label: "执行中",
        value: "1",
        detail: "W1 正常推进",
        targetFilter: "running",
      },
      {
        id: "active_workers",
        label: "活跃 Worker",
        value: "2",
        suffix: "/3",
        detail: "1 个槽位受预算约束",
        targetView: "scheduler",
      },
      {
        id: "blocked",
        label: "阻塞",
        value: "2",
        detail: "较 1 小时前",
        detailEmphasis: "+1",
        tone: "danger",
        targetFilter: "blocked",
      },
      {
        id: "completed_today",
        label: "今日完成",
        value: "12",
        detail: "8 Issue · 4 个门禁",
      },
      {
        id: "budget_health",
        label: "预算健康",
        value: "96%",
        detail: "使用 71% · 计划 68%",
        tone: "success",
        targetView: "scheduler",
      },
    ],
  },
  tasks: globalTasks,
};
